In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [5]:
x = df.iloc[:,:-1].values
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [6]:
y = df.iloc[:, -1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [7]:
le = LabelEncoder()
x[:,10] = le.fit_transform(x[:,10])
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [8]:
ct_slope = ColumnTransformer([('slope', OneHotEncoder(), [10])], remainder='passthrough')
x = ct_slope.fit_transform(x)
x

array([[1. , 0. , 0. , ..., 2.3, 0. , 1. ],
       [1. , 0. , 0. , ..., 3.5, 0. , 2. ],
       [0. , 0. , 1. , ..., 1.4, 0. , 2. ],
       ...,
       [0. , 1. , 0. , ..., 3.4, 2. , 3. ],
       [0. , 1. , 0. , ..., 1.2, 1. , 3. ],
       [0. , 1. , 0. , ..., 0. , 1. , 2. ]])

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
ss = StandardScaler()
x = ss.fit_transform(x)
x

array([[ 3.66450153, -0.92676626, -0.93914194, ...,  1.08733806,
        -0.71442887, -2.14887271],
       [ 3.66450153, -0.92676626, -0.93914194, ...,  2.12257273,
        -0.71442887, -0.51292188],
       [-0.27288841, -0.92676626,  1.06480177, ...,  0.31091206,
        -0.71442887, -0.51292188],
       ...,
       [-0.27288841,  1.07902072, -0.93914194, ...,  2.03630317,
         1.24459328,  1.12302895],
       [-0.27288841,  1.07902072, -0.93914194, ...,  0.13837295,
         0.26508221,  1.12302895],
       [-0.27288841,  1.07902072, -0.93914194, ..., -0.89686172,
         0.26508221, -0.51292188]])

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=380)

In [13]:
params = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None ,2, 3, 5],
    'min_samples_split': [1, 2, 3, 5],
    'min_samples_leaf' : [1, 2, 3, 4, 5],
    'max_leaf_nodes' : [2, 3, 5, 7],
    'max_features': ['auto', 'sqrt', 'log2']
}
gsh = GridSearchCV(DecisionTreeClassifier(), param_grid=params,scoring='f1', cv=3, n_jobs=-1, verbose=10)


In [14]:
gsh.fit(x,y)
print("Best Parameters:", gsh.best_params_)
print("Best Score:", gsh.best_score_)

Fitting 3 folds for each of 2880 candidates, totalling 8640 fits
Best Parameters: {'criterion': 'entropy', 'max_depth': 5, 'max_features': 'log2', 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'min_samples_split': 1}
Best Score: 0.8536572286572287


In [15]:
dtree = DecisionTreeClassifier(criterion='entropy', max_depth=5, max_features='log2', max_leaf_nodes=7, min_samples_leaf=4,
                               min_samples_split=1, random_state=42)
dtree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, max_features='log2',
                       max_leaf_nodes=7, min_samples_leaf=4,
                       min_samples_split=1, random_state=42)

In [16]:
p = dtree.predict(x_test)
print(metrics.classification_report(y_test,p))

              precision    recall  f1-score   support

           0       0.65      0.71      0.68       110
           1       0.74      0.68      0.71       133

    accuracy                           0.70       243
   macro avg       0.69      0.70      0.69       243
weighted avg       0.70      0.70      0.70       243



In [ ]:
params_r = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None ,2, 3, 5],
    'min_samples_split': [1, 2, 3, 5],
    'min_samples_leaf' : [1, 2, 3, 4, 5],
    'max_leaf_nodes' : [2, 3, 5, 7],
    'max_features': ['auto', 'sqrt', 'log2']
}
gsh_r = GridSearchCV(DecisionTreeClassifier(), param_grid=params_r,scoring='Recall', cv=3, n_jobs=-1, verbose=10)


In [ ]:
gsh_r.fit(x,y)
print("Best Parameters:", gsh_r.best_params_)
print("Best Score:", gsh_r.best_score_)

In [ ]:
from sklearn.svm import SVC

In [ ]:
param = {'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
        'C' : [0.1, 0.11, 10, 15, 17],
         'gamma' : ['scale', 'auto', 0.18,2, 10, 100],
         'decision_function_shape' : ['ovo', 'ovr'],
         'degree' : [1, 2, 3]
        } 
gsvm = GridSearchCV(SVC(), param_grid=param,scoring='f1', cv=3, n_jobs=-1, verbose=10)

In [ ]:
gsvm.fit(x_train,y_train)
print("Best Parameters:", gsvm.best_params_)
print("Best Score:", gsvm.best_score_)

In [ ]:
dsvm = SVC(C=0.1, decision_function_shape='ovo', degree=1, gamma='auto', kernel='poly', random_state=0)
dsvm.fit(x_train,y_train)

In [ ]:
p = dsvm.predict(x_test)
print(metrics.classification_report(y_test,p))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
prm = {'n_estimators' : [100, 200, 300],
      'criterion': ['gini', 'entropy', 'log_loss'],
        'max_depth': [None ,2, 3, 5],
    'min_samples_split': [1, 2, 3, 5],
    'min_samples_leaf' : [1, 2, 3, 4, 5],
    'max_leaf_nodes' : [2, 3, 5, 7],
    'max_features': ['auto', 'sqrt', 'log2']
      }
grf = GridSearchCV(RandomForestClassifier(), param_grid=params,scoring='f1', cv=3, n_jobs=-1, verbose=10)

In [ ]:
grf.fit(x_train,y_train)  
print("Best Parameters:", grf.best_params_)
print("Best Score:", grf.best_score_)

In [ ]:
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)