In [ ]:
import numpy as np

In [ ]:
n = 4

In [ ]:
num = int(input("Please Enter Your Number: "))
df = np.array([np.random.randint(100) for i in range(num)])
print(df)

max_number = np.max(df)
print(max_number)
if max_number > 70:
    print(f"{max_number} is greater than 70 --> win")
else:
    print(f"{max_number} is smaller than 70 --> Fail")

Please Enter Your Number: 5
[99 83 21 96 58]
99
99 is greater than 70 --> win


65 is smaller than 70 --> Fail


In [2]:
import numpy as np
from numpy import random


number = int(input ('Please enter your number: '))
x = random.choice(100, size=number)
print(x)

max_number = np.max(x)
print(max_number)
if max_number >70:
    print('WIN')
else:
    print('FAIL')

Please enter your number: 3
[55 72 41]
72
WIN


In [3]:

num = 3
n = np.random.choice(100, size=num)
print(n)
type(n)

[33 61 17]


numpy.ndarray

In [7]:
a = np.random.choice(100, size=3)
print(a)

[ 7 39 95]
