# **Quick Sort**

یکی از پرکاربردترین الگوریتم‌های مرتب‌سازی است که در پایتون نیز قابل پیاده‌سازی است این الگوریتم با استفاده از روش تقسیم و حل، آرایه‌ای را به دو بخش تقسیم کرده و به صورت بازگشتی برای هر بخش، همین روند را تکرار می‌کند تا زمانی که آرایه به صورت کامل مرتب شود.




در پیاده‌سازی الگوریتم در پایتون، به طور معمول از یک تابع بازگشتی استفاده می‌شود. در هر مرحله، یک عنصر را به عنوان پیوت انتخاب کرده و تمام عناصر کوچکتر از پیوت را در یک بخش و تمام عناصر بزرگتر از پیوت را در بخش دیگر قرار می‌دهیم. سپس همین عملیات را برای هر بخش تکرار می‌کنیم تا زمانی که آرایه به صورت کامل مرتب شود.

**Method 1**

In [ ]:
import numpy as np

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        left = np.array([x for x in arr[1:] if x < pivot])
        right = np.array([x for x in arr[1:] if x >= pivot])
        return np.concatenate([quicksort(left), [pivot], quicksort(right)])

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_arr = quicksort(arr)
print(sorted_arr)

[1. 1. 2. 3. 3. 4. 5. 5. 5. 6. 9.]


**Method 2**

In [7]:
import numpy as np

def quicksort2(arr):
    q = np.sort(arr, kind="quicksort")
    return q

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
obj_quick = quicksort2(arr)
print(obj_quick)

[1 1 2 3 3 4 5 5 5 6 9]


# **Heap Sort**

در این الگوریتم ابتدا یک ساختار داده ای است که  به صورت درختی برای نگهداری عناصر استفاده میشود و دارای دو ویژگی اصلی میباشد:اولی عنصر در بزرگترین یا کوچکترین عنصر است و دومین ویژگی بزرگتر آن اینه که هر گره از فرزندان خود است سپس عناصر یکی خارج شده و در یک لیست جدید به ترتیب قرار میگیرند که در نهایت این لیست مرتب شده بدست می آید

### **Method 1**

In [ ]:
import numpy as np
from heapq import heapify, heappop

def heap_sort(arr):
    heap = arr.tolist()
    heapify(heap)

    sorted_arr = np.zeros(len(arr), dtype=arr.dtype)
    for i in range(len(arr)):
        sorted_arr[i] = heappop(heap)

    return sorted_arr

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
heap = heap_sort(arr)
print(heap)

[1 1 2 3 3 4 5 5 5 6 9]


### **Method 2**

In [8]:
def heapsort(arr):
    h = np.sort(arr, kind="heapsort")
    return h

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
obj = heapsort(arr)
print(obj)

[1 1 2 3 3 4 5 5 5 6 9]


# **Merge Sort**

در این الگوریتم لیست به دو قسمت مساوی تقسیم شده و سپس برای هر قسمت به صورت بازگشتی انجام میشود این عملیات در نهایت دو لیست مرتب شده در کنار هم قرار داده میشوند و به کمک این تابع لیست کاملا مرتب شده بدست می آید

### **Method 1**

In [1]:
import numpy as np

def mergesort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        left = mergesort(arr[:mid])
        right = mergesort(arr[mid:])
        return merge(left, right)

def merge(left, right):
    result = np.empty(len(left) + len(right), dtype=left.dtype)
    i = j = k = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result[k] = left[i]
            i += 1
        else:
            result[k] = right[j]
            j += 1
        k += 1
    result[k:] = left[i:] if i < len(left) else right[j:]
    return result

def merge_arrays(arr1, arr2):
    result = np.empty(len(arr1) + len(arr2), dtype=arr1.dtype)
    result[:len(arr1)] = arr1
    result[len(arr1):] = arr2
    return mergesort(result)

In [ ]:
arr1 = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
arr2 = np.array([8, 9, 7, 6, 4, 5, 3, 2, 1])
sorted_arr = merge_arrays(arr1, arr2)
print(sorted_arr)

[1 1 1 2 2 3 3 3 4 4 5 5 5 5 6 6 7 8 9 9]


### **Method 2**

In [4]:
import numpy as np

def merge_sort2(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr) // 2
        left = merge_sort2(arr[:mid])
        right = merge_sort2(arr[mid:])
        return merge(left, right)

def merge(left, right):
    result = np.empty(len(left) + len(right), dtype=left.dtype)
    i = j = k = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result[k] = left[i]
            i += 1
        else:
            result[k] = right[j]
            j += 1
        k += 1
    result[k:] = left[i:] if i < len(left) else right[j:]
    return result

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
sorted_arr = merge_sort2(arr)
print(sorted_arr)

[1 1 2 3 3 4 5 5 5 6 9]


**Method 3**

In [2]:
import numpy as np
def merge_sort3(arr):
    m = np.sort(arr, kind="mergesort")
    return m

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
obj = merge_sort3(arr)
print(obj)

[1 1 2 3 3 4 5 5 5 6 9]
